FROM elixir:1.8 as builder

# install hex package manager
RUN mix local.hex --force
RUN mix local.rebar --force

# install the latest Phoenix
RUN mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez --force

# install NodeJS and NPM
RUN curl -sL https://deb.nodesource.com/setup_9.x -o nodesource_setup.sh
RUN bash nodesource_setup.sh
RUN apt-get install nodejs
# create our app folder and copy our code in it
WORKDIR /opt/app
COPY . .

ENV MIX_ENV=prod

# get deps
RUN mix deps.get --only prod

# compile code
RUN mix compile

#build assets with webpack
RUN mix phx.digest

# create release 
RUN mix release

# run the release
# CMD [ "_build/prod/rel/api_umbrella/bin/api_umbrella", "foreground" ]


FROM alpine:latest

RUN apk update && \
    apk add --no-cache \
    bash \
    openssl-dev

ENV PORT=4000 MIX_ENV=prod
ENV BASIC_AUTH_USERNAME=user BASIC_AUTH_PASSWORD=password BASIC_AUTH_REALM="Production realm"
WORKDIR /opt/app
COPY --from=builder /opt/app/_build/prod/rel/api_umbrella .
EXPOSE 4000
CMD [ "/opt/app/api_umbrella/bin", "foreground" ]
# CMD [ "/bin/sh" ]

