version: '3.5'

services:
  web:
    image: api_umbrella:latest
    depends_on:
        - db
    ports:
        - "4000:4000"
    env_file:
        - config/docker.env
  db:
    image: postgres:10-alpine
    volumes:
        - "~/volumes/postgres:/var/lib/postgresql/data"
    ports:
        - "5432:5432"
    env_file:
        - config/docker.env